# Generated by Django 4.1.1 on 2022-09-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(default='Admin del sitio', max_length=50)),
                ('slug', models.SlugField()),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
