# Generated by Django 4.1.1 on 2022-09-24 21:13

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='image',
            field=models.ImageField(default=None, upload_to=pathlib.PureWindowsPath('C:/Users/Pedro/Desktop/web_caribe/juegos_caribe_web/media')),
            preserve_default=False,
        ),
    ]
