# Generated by Django 4.1.1 on 2022-09-22 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0004_alter_team_name'),
        ('cronograma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportEventSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('competitors', models.ManyToManyField(to='deportes.competitor')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.sport')),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='SportEventTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.sport')),
                ('teams', models.ManyToManyField(to='deportes.team')),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.DeleteModel(
            name='SportEvent',
        ),
    ]
