# Generated by Django 4.1.1 on 2022-09-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma', '0002_sporteventsingle_sporteventteam_delete_sportevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporteventsingle',
            name='location',
            field=models.CharField(default='CEDER', max_length=50),
            preserve_default=False,
        ),
    ]
