# Generated by Django 4.1.1 on 2022-09-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma', '0003_sporteventsingle_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporteventteam',
            name='location',
            field=models.CharField(default='SEDER', max_length=50),
            preserve_default=False,
        ),
    ]
