# Generated by Django 4.1.1 on 2022-09-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\Pedro\\Desktop\\web_caribe\\juegos_caribe_web/media'),
        ),
    ]
