# Generated by Django 4.1.1 on 2022-09-26 07:50

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('C:/Users/Dukagin/Documents/Projects MATCOM/Juegos-caribe-web/juegos_caribe_web/media')),
        ),
    ]
