# Generated by Django 4.1.1 on 2022-09-30 04:00

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('C:/Users/Pedro/Desktop/web_caribe/juegos_caribe_web/media')),
        ),
    ]
