# Generated by Django 4.1.1 on 2022-09-24 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cronograma', '0002_sporteventsingle_sporteventteam_delete_sportevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultTeamMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', models.TextField()),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='cronograma.sporteventteam')),
            ],
        ),
        migrations.CreateModel(
            name='ResultSingleMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', models.TextField()),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='cronograma.sporteventsingle')),
            ],
        ),
    ]
