# Generated by Django 4.1.1 on 2022-09-22 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino'), ('other', 'Otro')], default='other', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('competitor_type', models.CharField(choices=[('team', 'Equipo'), ('single', 'Individual')], default='team', max_length=15)),
                ('competition_type', models.CharField(choices=[('rounds', 'Eliminatoria'), ('score', 'Puntuacion')], default='rounds', max_length=15)),
                ('participants', models.ManyToManyField(to='deportes.competitor')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.faculty')),
                ('members', models.ManyToManyField(to='deportes.competitor')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.sport')),
            ],
        ),
        migrations.AddField(
            model_name='competitor',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.faculty'),
        ),
    ]
