# Generated by Django 4.1.1 on 2022-09-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0003_competitor_sports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='Sin Nombre', max_length=100),
        ),
    ]
